<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>assets\umamusumedarkmode.ico</ApplicationIcon>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\umamusumedarkmode.ico" />
    <Resource Include="assets\umamusumedarkmode.jpg" />
    <None Include="assets\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
